### ISSUE TITLE
Include Script-Requestor tag on requests

### ISSUE THREAD

**Issue by tzarebczan** [FAIR-Protocol/fair-protocol-sdk#47]
If interacting with the SDK directly, you can query by the transaction owner. 

If you're interacting via a proxy that makes transactions on behalf of users, the transaction owner is always the same. 

By allowing a tag to be populated on the request itself called Script-Requestor (or whatever name you choose), we can allow for easier querying. I do realize this can be included in User Defined Tags tag, but it's harder to search by. 

Our plan is to set is as whatever we pass to firstOwner in Init-State, so this can either happen directly or by setting the tag via the SDK apis, i..e similar to n-images tag. So if it's not set, maybe set to the transaction owner address? 

This will provide a uniform way to query back requests. This can be potentially helpful if a response hasn't been received, in order to give the user a better picture of all outgoing vs fulfilled requests.

**Comment by l-silvestre** [comment]
defined tag name as "Request-Caller"
